---
name: Deploy Image

on:
  workflow_dispatch:
     - 'deploy-img'

jobs:
  deqloy-img:
   name: Deploy an image
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deploy
        run: |
         docker container run --detach --publish 3000:80  ${{ vars.DOCKER_IMAGE }}
         docker ps
         while ! curl --retry 10 --retry-delay 5 -v http://0.0.0.0:3000 >/dev/null; do sleep 1; done