---
name: Deploy Image

on:
  workflow_dispatch:

jobs:
  deqloy-img:
   name: Deploy an image
   runs-on: ubuntu-latest
   steps:
      - name: ShowVars
        run: |
         echo "Repository variable : $vars.DOCKER_IMAGE"

      - name: Deploy
        run: |
         docker container run --detach --publish 3000  ${{ vars.DOCKER_IMAGE }}
         docker ps
         ip route | grep docker0 | awk '{print $9}'

      - name: test
        run: |
         while ! curl --retry 10 --retry-delay 5 -v http://172.17.0.1:3000 >/dev/null; do sleep 1; done
