---
name: Deploy Image

on:
  workflow_dispatch:

jobs:
  deqloy-img:
   name: Deploy an image
   runs-on: ubuntu-latest
   container:
      image: ${{ vars.DOCKER_IMAGE}}
      ports:
        - 3000
   steps:
      - name: ShowVars
        run: |
         echo "Repository variable : $DOCKER_IMAGE"
      - name: Deploy
        run: |
         apt-get update; apt-get install -y curl
         # docker container run --detach --publish 3000  ${{ vars.DOCKER_IMAGE }}
         # docker ps
         ip route | grep docker0 | awk '{print $9}'
      - name: test
        run: |
         while ! curl --retry 10 --retry-delay 5 -v http://0.0.0.0:3000 >/dev/null; do sleep 1; done
